version: '3.7'

services:
  server:
    build:
      context: ./server
      target: dev
    image: autotest-server-dev:1.1.0
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - REDIS_URL=redis://redis:6379/
      - REGISTRY_HOST=localhost:5001 # optional: use if you want to store images to a custom registry
      - VOLUME_DRIVER=local
      - VOLUME_DRIVER_OPTS={} # opts are json string
    depends_on:
      - redis
    deploy:
      replicas: 2

  redis: # TODO: only have one redis container for the api and the backend
    image: redis:7.0.4-alpine
    volumes:
      - redis_autotest:/data
    ports:
    - 6379

  registry:
    image: registry:2.8.1
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:5001
    volumes:
      - registry:/var/lib/registry
    ports:
      - '5001:5001'

volumes:
  postgres_autotest:
  redis_autotest:
  workspace:
