version: '3.7'

services:
  backend-dev:
    build:
      target: dev
    image: autotest-backend-docker-dev:1.0.0
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - REDIS_URL=redis://localhost:6379/ # This value is required and should be set to point to your redis database
      - REGISTRY_URL=localhost:5001 # optional: use if you want to store images to a custom registry (see below)
    deploy:
      replicas: 2

  backend-prod:
    build:
      target: prod
    image: autotest-backend-docker:1.0.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - REDIS_URL=redis://localhost:6379/ # This value is required and should be set to point to your redis database
      - REGISTRY_URL=localhost:5001 # optional: use if you want to store images to a custom registry (see below)
    deploy:
      replicas: 2

  registry:
    image: registry:2.8.1
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:5001
    volumes:
      - registry:/var/lib/registry
    ports:
      - '5001:5001'
